name: greetings

on:
  workflow_dispatch:
  issues:
  pull_request:

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "欢迎"
          pr-message: "谢谢"
